defaults:
    url: "http://kava-i.de:4848/api/v2/search?q={}"
    verb: "get"

jobs:
    - url_params: ["Himmelsstriche"]
    - url_params: ["hünd"]
    - url_params: ["  hünd"]
    - url_params: ["  hünd  "]
    - url_params: ["hünd  "]
    - url_params: ["ändern  "]
    - url_params: ["ändern  +der"]
    - url: "http://kava-i.de:4848/api/v2/search?q={}"
    - url: "http://kava-i.de:4848/api/v2/search?{}"
      verb: "get"
    - url: "http://kava-i.de:4848/api/v2/search"
      verb: "get"
